services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  ui:
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres:${PASSWORD}@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
    restart: unless-stopped

  caddy:
    image: caddy:2.9-alpine
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data

volumes:
  pgdata:
  pgadmin:
  caddy:
