// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CategoriesToTarget struct {
	ID          int32
	DishID      pgtype.Int4
	CommodityID pgtype.Int4
	CategoryID  int32
}

type Category struct {
	ID   int32
	Name string
}

type Commodity struct {
	ID          int32
	SupplierID  int32
	Name        string
	Cost        int64
	Image       []byte
	Ingredients string
	Weight      int32
	Rating      pgtype.Numeric
}

type Courier struct {
	ID     int32
	Name   string
	Phone  string
	Rating pgtype.Numeric
}

type Discount struct {
	ID          int32
	Name        string
	Description string
	Type        string
	Terms       []byte
	Active      bool
}

type DiscountToTarget struct {
	ID          int32
	DishID      pgtype.Int4
	CommodityID pgtype.Int4
	DiscountID  int32
}

type Dish struct {
	ID          int32
	SupplierID  int32
	Name        string
	Cost        int64
	Image       []byte
	Ingredients pgtype.Text
	Weight      int32
	Calories    int32
	Allergens   string
	Rating      pgtype.Numeric
}

type Order struct {
	ID            int32
	UserID        pgtype.Int4
	Timestamp     pgtype.Timestamp
	SourceAddress pgtype.Text
	TargetAddress pgtype.Text
	CourierID     pgtype.Int4
	Status        pgtype.Text
	PaymentID     pgtype.Int4
	DiscountID    pgtype.Int4
}

type OrdersComposition struct {
	ID          int32
	OrderID     int32
	DishID      pgtype.Int4
	CommodityID pgtype.Int4
}

type Payment struct {
	ID        int32
	Method    string
	CardID    pgtype.Int4
	Timestamp pgtype.Timestamp
	Status    string
}

type Supplier struct {
	ID            int32
	Name          string
	WorkTimeStart pgtype.Time
	WorkTimeEnd   pgtype.Time
	Rating        pgtype.Numeric
	Address       string
}

type User struct {
	ID           int32
	Name         pgtype.Text
	Surname      pgtype.Text
	Email        pgtype.Text
	Phone        pgtype.Text
	PasswordHash pgtype.Text
}

type UserAddress struct {
	ID      int32
	UserID  int32
	Address string
}

type UserCard struct {
	ID     int32
	UserID int32
	Number string
}
